var app = new Vue({
    el: '#app',
    data: {
        videodata:[
            {
                src:'../../index/video/240.mp4',
                title:'什么是直播？',
            },
            {
                src:'../../index/video/240.mp4',
                title:'什么是直播？',
            },
            {
                src:'../../index/video/240.mp4',
                title:'什么是直播？',
            },
            {
                src:'../../index/video/240.mp4',
                title:'什么是直播？',
            },
            {
                src:'../../index/video/240.mp4',
                title:'什么是直播？',
            },
            {
                src:'../../index/video/240.mp4',
                title:'什么是直播？',
            },
            {
                src:'../../index/video/240.mp4',
                title:'什么是直播？',
            },
            {
                src:'../../index/video/240.mp4',
                title:'什么是直播？',
            }
        ],
        luntandata:[
            {
                src:'../../common/img/images/img1.png',
                title:'什么是论坛？',
            },
            {
                src:'../../common/img/images/img2.png',
                title:'什么是论坛？',
            },
            {
                src:'../../common/img/images/img1.png',
                title:'什么是论坛？',
            },
            {
                src:'../../common/img/images/img2.png',
                title:'什么是论坛？',
            },
            {
                src:'../../common/img/images/img1.png',
                title:'什么是论坛？',
            },
            {
                src:'../../common/img/images/img2.png',
                title:'什么是论坛？',
            },
            {
                src:'../../common/img/images/img1.png',
                title:'什么是论坛？',
            },
            {
                src:'../../common/img/images/img2.png',
                title:'什么是论坛？',
            },
        ],
        user_info:[
            {
                name:'Mr.林',
                level:'大师',
                time:'2017-6-05 12:00',
                txt:'贴吧类容贴吧类容贴吧类容贴吧类容贴吧类容类容贴吧类容贴吧类容贴贴吧,类容贴吧类容贴吧类,容贴吧类容贴吧类容贴吧类容贴吧类容,贴吧类容贴吧类容贴吧类,容贴吧类容贴吧类容贴吧,类容贴吧类容贴吧类容贴,吧类容贴吧类容贴吧类容贴,吧类容贴吧类容,贴吧类容贴吧类容,贴吧类容贴吧类容贴吧类容贴吧,类容贴吧类容,贴吧类容贴吧类容贴吧类容贴吧类容贴吧类容,贴吧类容贴吧类容贴吧类容贴吧类容贴'
            },
            {
                name:'Mr.林',
                level:'大师',
                time:'2017-6-05 12:00',
                txt:'贴吧类容贴吧类容贴吧类容贴吧类容贴吧类容类容贴吧类容贴吧类容贴贴吧,类容贴吧类容贴吧类,容贴吧类容贴吧类容贴吧类容贴吧类容,贴吧类容贴吧类容贴吧类,容贴吧类容贴吧类容贴吧,类容贴吧类容贴吧类容贴,吧类容贴吧类容贴吧类容贴,吧类容贴吧类容,贴吧类容贴吧类容,贴吧类容贴吧类容贴吧类容贴吧,类容贴吧类容,贴吧类容贴吧类容贴吧类容贴吧类容贴吧类容,贴吧类容贴吧类容贴吧类容贴吧类容贴'
            },
            {
                name:'Mr.林',
                level:'大师',
                time:'2017-6-05 12:00',
                txt:'贴吧类容贴吧类容贴吧类容贴吧类容贴吧类容类容贴吧类容贴吧类容贴贴吧,类容贴吧类容贴吧类,容贴吧类容贴吧类容贴吧类容贴吧类容,贴吧类容贴吧类容贴吧类,容贴吧类容贴吧类容贴吧,类容贴吧类容贴吧类容贴,吧类容贴吧类容贴吧类容贴,吧类容贴吧类容,贴吧类容贴吧类容,贴吧类容贴吧类容贴吧类容贴吧,类容贴吧类容,贴吧类容贴吧类容贴吧类容贴吧类容贴吧类容,贴吧类容贴吧类容贴吧类容贴吧类容贴'
            },
        ],

        value:'',
        hide:'',
        hides:false,
        message:[],
    },
    created: function () {
    },
    methods: {
        show:function(index){
            this.hide=index;
        },
        submit:function(index) {
            console.log(this.user_info)
            if(this.value===''){
                return false
            }else {
                this.message.push({
                    content:this.value
                });
                this.value='',
                this.hides=true,
                this.hide=false
            }
        },
        cancel:function(){
            this.hide=false,
            this.value=''
        },
        //预约咨询
        yuyue(ev){
            $(ev.target).addClass('hiactive').siblings().removeClass('hiactive');
        },
        /*关注*/
        guanzhu(ev){
            $(ev.target).addClass('hiactive').siblings().removeClass('hiactive');
        },
        //nav高亮
		searchfun(ev){
			$(ev.target).addClass('hoverhight').siblings().removeClass('hoverhight');
            window.location.href='AskQuestions_b.html';
		},
        //nav跳转
        searchcli(ev,a){
            $(ev.target).addClass('myhight').siblings().removeClass('myhight');
            //alert(a);
            window.location.href=''+a+'.html';
        },

        //视频
        clickfun(ev,a){
            $(ev.target).addClass('myacbgd').parent().siblings().find('a').removeClass('myacbgd');
            $('.'+a+'').parent().fadeIn();
            $('.'+a+'').parent().siblings().hide();
            console.log($('.'+a+''));
        },
        playvideo(ev,index){
            var videoobj = document.getElementsByClassName("videoobj")[index];
            console.log(videoobj);
            if(videoobj.paused){
                videoobj.play();
                //alert()
            }else{
                videoobj.pause();
            }
        },
        //更多
        zkmore(ev){
            $(ev.target).parent().siblings('.mcontbox').find('.myno').slideToggle();
        },
        zhibomore(ev){
            if(!$(ev.target).hasClass('clicked')){
                $(ev.target).addClass("clicked");
                $('.mozhibo').css({'height':'auto'});
            }else{
                $(ev.target).removeClass("clicked");
                $('.mozhibo').css({'height':'107px'});
            }
        },
        //tab
        myultab(ev,a){
            $(ev.target).addClass('maccss').siblings('a').removeClass('maccss');
            $("."+a+"").fadeIn();
            $("."+a+"").siblings('.multab').hide();
        },
        btnfun(ev){
            $(ev.target).addClass('btnaccss').parent().siblings().find('a').removeClass('btnaccss');
        },
    },
})